import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Наш проект",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            {/*Боди передать класснаме какой то*/}
            <body >
                <nav className={styles.nav}>
                    <ul>
                        <li><Link href={'/'}>Главная</Link></li>
                        <li>Курсы</li>
                        <li>Для детей</li>
                        <li><Link href={'/about'}>О нас</Link></li>
                        <li><Link href={'/courses/typescript'}>Продукт</Link></li>
                        <li><Link href={'/sdfasdfaf'}>О нас 3</Link></li>
                        {/*Линк позволяет загружать страницу под капотом, благодаря этому при переходе на страницу у нас она не рендериться*/}
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    );
}

// сначала смотрит файлы (favicon, robots и т.д.), потом  page потом layout. Для иконок лучше файловые.А методанные лучше в функции делать
// Для групп страниц layout, для индивидуальных использовть page