import type { Metadata } from "next";
import "./globals.css";
import styles from "./Layout.module.css";
import {Header} from "@/layout/Header/Header";
import {SideBar} from "@/layout/SideBar/SideBar";
import {Footer} from "@/layout/Footer/Footer";

export const metadata: Metadata = {
  title: "Наш проект",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body>
        <div className={styles.wrapper}>
            <Header className={styles.header} />
            <SideBar className={styles.sideBar} />
            <div className={styles.body}>
                {children}
            </div>
            <Footer className={styles.footer} />
        </div>
        </body>
        </html>
  );
}

// сначала смотрит файлы (favicon, robots и т.д.), потом  page потом layout. Для иконок лучше файловые.А методанные лучше в функции делать
// Для групп страниц layout, для индивидуальных использовть page
