import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../(site)/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Наш проект",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div>Авторизация</div>
      {children}
      </body>
    </html>
  );
}

// сначала смотрит файлы (favicon, robots и т.д.), потом  page потом layout. Для иконок лучше файловые.А методанные лучше в функции делать
// Для групп страниц layout, для индивидуальных использовть page
